version: 0.2

#TODO: Move all constatns to environment variables
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - start-dockerd
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - pip install -r src/requirements.txt
      - bash src/setup.sh $FRAMEWORK
  build:
    commands:
      - echo Fetching s3 binary for gpu...
      - aws s3 cp s3://aws-mxnet-builds/2020-06-09/aws_mxnet_cu101mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl mxnet/training/docker/artifacts/aws_mxnet_cu101mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl
      - echo Copy to inference folder...
      - cp mxnet/training/docker/artifacts/aws_mxnet_cu101mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl mxnet/inference/docker/artifacts/aws_mxnet_cu101mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl
      - echo Fetching s3 binary for cpu...
      - aws s3 cp s3://aws-mxnet-builds/2020-06-09/aws_mxnet_mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl mxnet/training/docker/artifacts/aws_mxnet_mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl
      - echo Copy to inference folder...
      - cp mxnet/training/docker/artifacts/aws_mxnet_mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl mxnet/inference/docker/artifacts/aws_mxnet_mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        if expr "${CODEBUILD_BUILD_ARN}" : ".*tensorflow-1" >/dev/null; then
          python src/main.py --buildspec $FRAMEWORK/buildspec-tf1.yml --framework $FRAMEWORK
        else
          python src/main.py --buildspec $FRAMEWORK/buildspec.yml --framework $FRAMEWORK
        fi
  post_build:
    commands:
      - echo Build step finished on `date`
      - echo Starting test jobs
      - python src/start_testbuilds.py
artifacts:
  files:
    - $HOME/test_type_images.json
  name: DLC_IMAGES_JSON
  discard-paths: yes

